Numpy matematiksel işlemleri yapabileceğimiz bir kütüphanedir.
İmport etmeden önce pip install ile yüklememiz gerekir.

In [ ]:
pip install numpy
%pip install numpy
!pip install numpy

In [3]:
import numpy as np

In [ ]:
pip install --upgrade numpy  #numpy'ınızı upgrade eder.

In [4]:
my_list = [1, 2, 3] #Bir dize oluşturduk
my_list

[1, 2, 3]

In [5]:
np.array(my_list) #Numpy arrayi olarak dönüştürdük

array([1, 2, 3])

In [6]:
np.array([1,3,4,5.5,7,9]) #İçerisinde float olduğu için intler de floata dönüştüler.

array([1. , 3. , 4. , 5.5, 7. , 9. ])

In [7]:
np.array([2,3,4], dtype=float) #dtype ile bu şekilde de dönüştürebiliriz

array([2., 3., 4.])

### 2D - Matrix arrayler oluşturma

In [9]:
np.array([[1,2],[8,9]]) #bu şekilde matrix bir yapıda da oluşturabiliriz. Çok boyutlu olur 2D şeklinde.

array([[1, 2],
       [8, 9]])

In [10]:
my_list2 = [[1,2,3],[4,5,6],[7,8,9]] #Normal listeleri de array olarak dönüştürebiliriz.
my_list2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_list2) #ta daaaa dönüştü

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 3D array oluşturma

In [12]:
np.array([[[1,2],[4,5],[7,9]]]) # İpucu: Arraylerin kaç boyutlu olduklarını parantez sayılarından sayarak anlayabiliriz.

array([[[1, 2],
        [4, 5],
        [7, 9]]])

### shape & reshape

**shape:**  Numpy array boyutunu yani kaç satır ve sütundan oluştuğunu gösteren bir tuple döndürür. Örn: 3,3

​


In [15]:
my_arr = np.array(my_list2)
my_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
my_arr.shape

(3, 3)

In [19]:
np.array([1,2,3,4,5]).shape #Tek boyutlu arraylerde (5,) şeklinde sayı adeti kadar döndürür.

(5,)

**reshape():**  Numpy array’i yeniden şekillendirmek istediğimizde yani satır ve sütun sayısını değiştirmek istediğimizde reshape() metodunu kullanabiliriz.
- Diziyi belirtilen yeni şekle getirerek yeni bir ndarray döndürür. Ancak, bu metod orijinal veriyi değiştirmez.
- Belirli boyutlar için "-1" değeri kullanılabilir, bu sayede NumPy otomatik olarak belirtilen diğer boyutlara uygun şekilde bu boyutu hesaplar.

In [22]:
my_arr_2 = np.array([[1,2,3],[4,5,6], [7,8,9],[10,11,12]]) #4,3
my_arr_2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [24]:
my_arr_2.reshape(3,4) #3,4 olarak değiştirdik.İçeriğini sırasına göre belirledi.

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
my_arr_2.reshape(3,5) #HATA. Matematiksel olarak tam bölünmezse eksik veya fazla elemandan dolayı oluşturamaz.

ValueError: cannot reshape array of size 12 into shape (3,5)

-1 değeri: Kaç tane olabiliyorsa o kadar olsun demektir.


In [28]:
my_arr_2.reshape(6,-1) #6 satır olsun, kaç tane olabiliyorsa o kadar da sütun olsun.

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [31]:
my_arr_2.reshape(-1,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])